### PR TITLE
Adding Unstructured.io ingest PDF notebook

### PR DESCRIPTION
**Pull request by evinaku**

### CODE REVIEW

**Review by kesmit13 — COMMENTED** [review]
You need to run the pre-commit check and fix those issues. See https://github.com/singlestore-labs/spaces-notebooks/blob/master/CONTRIBUTING.md.

**Review by kesmit13 — APPROVED** [review]

**Comment by kesmit13** [comment]
Can you run the pre-commit checks again locally and push the result? It looks like the notebook formatter is still finding things to be changed.

**Comment by oyeliseiev-ua** [comment]
@kesmit13 Looks like fixed

**Comment by oyeliseiev-ua** [comment]
Hi @kesmit13, we don't see this page on spaces webpage yet, can you deploy it please?

**Comment by kesmit13** [comment]
I just noticed the `meta.toml` was missing the `destinations=` field. I added it. The notebook should show up fairly soon now.

**Pull request merged**
