### PR TITLE
Notebook for cdc-sql

### PR DESCRIPTION
**Pull request by sudo-savitaj**
Ingest data from MONGODB® to SingleStore using SQL commands.

### CODE REVIEW

**Review by kesmit13 — CHANGES_REQUESTED** [review]
Rather than all of the `USE` commands, you should show an "Action Required" box that tells the user to select the database in the drop-down at the top of the notebook (see https://github.com/singlestore-labs/spaces-notebooks/blob/master/notebooks/getting-started-with-notebooks/notebook.ipynb for an example). 

Also, you should look over the SQL commands in the notebook and make the keyword casing more consistent (all upper-case). It starts off that way, but later in the notebook the casing is not consistent.

**Comment by sudo-savitaj** [comment]
> Rather than all of the `USE` commands, you should show an "Action Required" box that tells the user to select the database in the drop-down at the top of the notebook (see https://github.com/singlestore-labs/spaces-notebooks/blob/master/notebooks/getting-started-with-notebooks/notebook.ipynb for an example).
> 
> Also, you should look over the SQL commands in the notebook and make the keyword casing more consistent (all upper-case). It starts off that way, but later in the notebook the casing is not consistent.

@kesmit13 I knowingly added "use" in all commands so that user doesnt run into the error, will this force into user selecting database before proceeding

**Comment by kesmit13** [comment]
The coding style that's been established in all of the other notebooks is to select the database at the top of the notebook. I think we should stick to it so they are consistent. The error won't happen if they select the database at the top. It also ensures that any connections make directly with the Python client, SQLAlchemy, or Ibis also work correctly.

**Comment by sudo-savitaj** [comment]
> The coding style that's been established in all of the other notebooks is to select the database at the top of the notebook. I think we should stick to it so they are consistent. The error won't happen if they select the database at the top. It also ensures that any connections make directly with the Python client, SQLAlchemy, or Ibis also work correctly.

on it make changes

**Comment by kesmit13** [comment]
@sudo-savitaj I'll be here tomorrow, and all this week. So I can still approve when it comes through.

**Comment by sudo-savitaj** [comment]
> @sudo-savitaj I'll be here tomorrow, and all this week. So I can still approve when it comes through.

cool thank you so much.. Ill push changes post testing once cluster creation issue is resolved

**Comment by sudo-savitaj** [comment]
@kesmit13 pushed suggested changes, please review PR.

**Comment by kesmit13** [comment]
Everything looks good as far as content goes. It looks like the pre-commit checks are failing though. Can you install and run those (see https://github.com/singlestore-labs/spaces-notebooks/blob/master/CONTRIBUTING.md)?

**Review by kesmit13 — APPROVED** [review]

**Pull request merged**
