### PR TITLE
Modified Notebooks according to feedback

### PR DESCRIPTION
**Pull request by chetanthote**

### CODE REVIEW

**Review by kesmit13 — CHANGES_REQUESTED** [review]
Can you remove the `##Drop Pipeline` in the cell near the end. That's a SQL cell, so `#` is not a comment character. That type of comment should be in a markdown cell. You can move the drop database comment from the next cell in the same way.

Also, there is a space after the `else` in the last cell that should be removed.

**Comment by chetanthote** [comment]
Done

**Review by kesmit13 — APPROVED** [review]

**Comment by chetanthote** [comment]
I have resolved conficts but pre commit check is failing

**Comment by kesmit13** [comment]
> I have resolved conficts but pre commit check is failing

Can you just pull the changes into your clone and push them again? That will run the pre-commit checks. It looks like there's a formatting issue in the notebook file. I think that should fix it and be the end.

**Comment by kesmit13** [comment]
> > I have resolved conficts but pre commit check is failing
> 
> Can you just pull the changes into your clone and push them again? That will run the pre-commit checks. It looks like there's a formatting issue in the notebook file. I think that should fix it and be the end.

You'll probably have to run the pre-commits manually since you won't have any changes to commit until the run:
```
pre-commit run --all-files
```

**Pull request merged**
