### PR TITLE
adding warm up disk notebook

### PR DESCRIPTION
**Pull request by bpaul-singlestore**
Added a new notebook. Notebook runs through the process of warming up both the disk and index data files which live in object storage when resuming a workspace or attaching a database to workspace.

### CODE REVIEW

**Review by kesmit13 — COMMENTED** [review]
Is sqlalchemy used in the notebook? I see it being imported, but I don't see any uses of the functions from that package.

**Comment by bpaul-singlestore** [comment]
correct - sqlalchemy is not used. Do you need me to remove and push changes?

**Comment by kesmit13** [comment]
> correct - sqlalchemy is not used. Do you need me to remove and push changes?

It's better if we don't import things that aren't used. So if you can remove that, I'll approve this PR.

**Comment by bpaul-singlestore** [comment]
Yep makes sense - good catch. 

Line removed & change committed.

**Pull request merged**
