### PR TITLE
Rename folders/files

### PR DESCRIPTION
**Pull request by tiimgreen**
- renamed all directories to use `kebab-case`
- all notebook files are called `notebook.ipynb`
- notebook title is taken from the `meta.toml` file
- added a contributing guide with info about required structure

Will add an automated check later to ensure this structure is maintained

### CODE REVIEW

**Comment by kesmit13** [comment]
I don't like all files being called `notebook.ipynb`. I think the name should reflect what the title of the notebook would be. Having the directory be `kebab-case` with a more shorter, more general subject than the current notebook subject is fine, but I feel like we're losing some descriptiveness by generalizing the notebook names. This also locks us into a one-notebook-per-folder scheme as well.

**Comment by kesmit13** [comment]
I guess if this repo is intended purely for populating the Spaces web site the naming is fine. For casual browsing by users, I don't feel like the names are as helpful.

**Comment by tiimgreen** [comment]
I was conceptualising each folder as a "package" of sorts and I think it makes sense to have the same file names in that sense and all the config/info held in the toml file.

I would imagine anyone generally browsing notebooks would do so on the /spaces page as it gives a much better experience (and we should encourage people to do so)

**Comment by kesmit13** [comment]
I was viewing the repo as more than just a storage area for Spaces data, but it's probably fine to treat it that way.

**Comment by tiimgreen** [comment]
Good to merge then?

**Comment by kesmit13** [comment]
There is a Github action that packages the set of notebooks to be displayed in the portal when a new notebook is created. That is broken now (this includes the root-level `meta.toml` and `resources/package-samples.py`). Those need to be fixed yet. Did you want to do those, or did you just want me to fix them in a following change? They currently are failing, but no one is using them yet.

**Comment by kesmit13** [comment]
I just merged it as-is. I'll fix the packaging scripts this afternoon.

**Comment by tiimgreen** [comment]
Sweet, thanks for that!

**Pull request merged**
